// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMwlawu1KteVVMd9EndK65jD-y4r9e7XI',
    appId: '1:450895601405:web:36b1cfa09975b40dc5e894',
    messagingSenderId: '450895601405',
    projectId: 'chatting-app-f1b4b',
    authDomain: 'chatting-app-f1b4b.firebaseapp.com',
    storageBucket: 'chatting-app-f1b4b.appspot.com',
    measurementId: 'G-6LYJVK7R0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaAlnpHC2o-al1diBetthZ8Ahyezm_ZUk',
    appId: '1:450895601405:android:b11700d1f12c6c32c5e894',
    messagingSenderId: '450895601405',
    projectId: 'chatting-app-f1b4b',
    storageBucket: 'chatting-app-f1b4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLJ-4uwyKnVOk8_1S30DSV6CgSHvMfpog',
    appId: '1:450895601405:ios:49abf0e6e53c528cc5e894',
    messagingSenderId: '450895601405',
    projectId: 'chatting-app-f1b4b',
    storageBucket: 'chatting-app-f1b4b.appspot.com',
    iosClientId: '450895601405-8trttkkoitn9gcfbe0g21ekfitia650o.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLJ-4uwyKnVOk8_1S30DSV6CgSHvMfpog',
    appId: '1:450895601405:ios:9a4d4ffb1e87ad8dc5e894',
    messagingSenderId: '450895601405',
    projectId: 'chatting-app-f1b4b',
    storageBucket: 'chatting-app-f1b4b.appspot.com',
    iosClientId: '450895601405-8q759rk0fpq5t9odn103k4ftnd1056be.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApplication.RunnerTests',
  );
}
